# Generated by Django 4.0.4 on 2022-04-23 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=6)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_utilizacao', models.DateTimeField(verbose_name='date published')),
                ('materia', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=6)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_utilizacao', models.DateTimeField(verbose_name='date published')),
                ('materia', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=6)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_utilizacao', models.DateTimeField(verbose_name='date published')),
                ('materia', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
