# Generated by Django 4.0.4 on 2022-04-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atividades',
            table='Atividades',
        ),
        migrations.AlterModelTable(
            name='jogos',
            table='Jogos',
        ),
        migrations.AlterModelTable(
            name='videos',
            table='Videos',
        ),
    ]
