"""educaItu URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from atividades.views import index, home, sobre, contato, sign_in, sair, submitlogin, portugues, portuguesJogos, portuguesJogosPrimeiroAno, portuguesJogosSegundoAno, portuguesJogosTerceiroAno, portuguesJogosQuartoAno, portuguesJogosQuintoAno, portuguesAtividades, portuguesAtividadesPrimeiroAno, portuguesAtividadesSegundoAno, portuguesAtividadesTerceiroAno, portuguesAtividadesQuartoAno, portuguesAtividadesQuintoAno, portuguesVideos, portuguesVideosPrimeiroAno, portuguesVideosSegundoAno, portuguesVideosTerceiroAno, portuguesVideosQuartoAno, portuguesVideosQuintoAno, matematica, matematicaJogos, matematicaJogosPrimeiroAno, matematicaJogosSegundoAno, matematicaJogosTerceiroAno, matematicaJogosQuartoAno, matematicaJogosQuintoAno, matematicaAtividades, matAtivPrimeiroAno, matematicaAtividadesSegundoAno, matAtivTerceiroAno, matematicaAtividadesQuartoAno, matematicaAtividadesQuintoAno, matematicaVideos, matematicaVideosPrimeiroAno, matematicaVideosSegundoAno, matematicaVideosTerceiroAno, matematicaVideosQuartoAno, matematicaVideosQuintoAno, historia, historiaJogos, historiaJogosPrimeiroAno, historiaJogosSegundoAno, historiaJogosTerceiroAno, historiaJogosQuartoAno, historiaJogosQuintoAno, historiaAtividades, historiaAtividadesPrimeiroAno, historiaAtividadesSegundoAno, historiaAtividadesTerceiroAno, historiaAtividadesQuartoAno, historiaAtividadesQuintoAno, historiaVideos, historiaVideosPrimeiroAno, historiaVideosSegundoAno, historiaVideosTerceiroAno, historiaVideosQuartoAno, historiaVideosQuintoAno, geografia, geografiaJogos, geografiaJogosPrimeiroAno, geografiaJogosSegundoAno, geografiaJogosTerceiroAno, geografiaJogosQuartoAno, geografiaJogosQuintoAno, geografiaAtividades, geografiaAtividadesPrimeiroAno, geografiaAtividadesSegundoAno, geografiaAtividadesTerceiroAno, geografiaAtividadesQuartoAno, geografiaAtividadesQuintoAno, geografiaVideos, geografiaVideosPrimeiroAno, geografiaVideosSegundoAno, geografiaVideosTerceiroAno, geografiaVideosQuartoAno, geografiaVideosQuintoAno, ciencias, cienciasJogos, cienciasJogosPrimeiroAno, cienciasJogosSegundoAno, cienciasJogosTerceiroAno, cienciasJogosQuartoAno, cienciasJogosQuintoAno, cienciasAtividades, cienciasAtividadesPrimeiroAno, cienciasAtividadesSegundoAno, cienciasAtividadesTerceiroAno, cienciasAtividadesQuartoAno, cienciasAtividadesQuintoAno, cienciasVideos, cienciasVideosPrimeiroAno, cienciasVideosSegundoAno, cienciasVideosTerceiroAno, cienciasVideosQuartoAno, cienciasVideosQuintoAno, ingles, inglesJogos, inglesJogosPrimeiroAno, inglesJogosSegundoAno, inglesJogosTerceiroAno, inglesJogosQuartoAno, inglesJogosQuintoAno, inglesAtividades, inglesAtividadesPrimeiroAno, inglesAtividadesSegundoAno, inglesAtividadesTerceiroAno, inglesAtividadesQuartoAno, inglesAtividadesQuintoAno, inglesVideos, inglesVideosPrimeiroAno, inglesVideosSegundoAno, inglesVideosTerceiroAno, inglesVideosQuartoAno, inglesVideosQuintoAno

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('home/', home),
    path('sobre/', sobre),
    path('contato/', contato),
    path('login/', sign_in),
    path('logout/', sair),
    path('login/submit', submitlogin),
    path('portugues/', portugues),
    path('portugues/jogos', portuguesJogos),
    path('portugues/jogos/primeiroAno/', portuguesJogosPrimeiroAno),
    path('portugues/jogos/segundoAno/', portuguesJogosSegundoAno),
    path('portugues/jogos/terceiroAno/', portuguesJogosTerceiroAno),
    path('portugues/jogos/quartoAno/', portuguesJogosQuartoAno),
    path('portugues/jogos/quintoAno/', portuguesJogosQuintoAno),
    path('portugues/atividades', portuguesAtividades),
    path('portugues/atividades/primeiroAno/', portuguesAtividadesPrimeiroAno),
    path('portugues/atividades/segundoAno/', portuguesAtividadesSegundoAno),
    path('portugues/atividades/terceiroAno/', portuguesAtividadesTerceiroAno),
    path('portugues/atividades/quartoAno/', portuguesAtividadesQuartoAno),
    path('portugues/atividades/quintoAno/', portuguesAtividadesQuintoAno),
    path('portugues/videos', portuguesVideos),
    path('portugues/videos/primeiroAno/', portuguesVideosPrimeiroAno),
    path('portugues/videos/segundoAno/', portuguesVideosSegundoAno),
    path('portugues/videos/terceiroAno/', portuguesVideosTerceiroAno),
    path('portugues/videos/quartoAno/', portuguesVideosQuartoAno),
    path('portugues/videos/quintoAno/', portuguesVideosQuintoAno),
    path('matematica/', matematica),
    path('matematica/jogos', matematicaJogos),
    path('matematica/jogos/primeiroAno/', matematicaJogosPrimeiroAno),
    path('matematica/jogos/segundoAno/', matematicaJogosSegundoAno),
    path('matematica/jogos/terceiroAno/', matematicaJogosTerceiroAno),
    path('matematica/jogos/quartoAno/', matematicaJogosQuartoAno),
    path('matematica/jogos/quintoAno/', matematicaJogosQuintoAno),
    path('matematica/atividades', matematicaAtividades),
    path('matematica/atividades/primeiroAno/', matAtivPrimeiroAno),
    path('matematica/atividades/segundoAno/', matematicaAtividadesSegundoAno),
    path('matematica/atividades/terceiroAno/', matAtivTerceiroAno),
    path('matematica/atividades/quartoAno/', matematicaAtividadesQuartoAno),
    path('matematica/atividades/quintoAno/', matematicaAtividadesQuintoAno),
    path('matematica/videos', matematicaVideos),
    path('matematica/videos/primeiroAno/', matematicaVideosPrimeiroAno),
    path('matematica/videos/segundoAno/', matematicaVideosSegundoAno),
    path('matematica/videos/terceiroAno/', matematicaVideosTerceiroAno),
    path('matematica/videos/quartoAno/', matematicaVideosQuartoAno),
    path('matematica/videos/quintoAno/', matematicaVideosQuintoAno),
    path('historia/', historia),
    path('historia/jogos', historiaJogos),
    path('historia/jogos/primeiroAno/', historiaJogosPrimeiroAno),
    path('historia/jogos/segundoAno/', historiaJogosSegundoAno),
    path('historia/jogos/terceiroAno/', historiaJogosTerceiroAno),
    path('historia/jogos/quartoAno/', historiaJogosQuartoAno),
    path('historia/jogos/quintoAno/', historiaJogosQuintoAno),
    path('historia/atividades', historiaAtividades),
    path('historia/atividades/primeiroAno/', historiaAtividadesPrimeiroAno),
    path('historia/atividades/segundoAno/', historiaAtividadesSegundoAno),
    path('historia/atividades/terceiroAno/', historiaAtividadesTerceiroAno),
    path('historia/atividades/quartoAno/', historiaAtividadesQuartoAno),
    path('historia/atividades/quintoAno/', historiaAtividadesQuintoAno),
    path('historia/videos', historiaVideos),
    path('historia/videos/primeiroAno/', historiaVideosPrimeiroAno),
    path('historia/videos/segundoAno/', historiaVideosSegundoAno),
    path('historia/videos/terceiroAno/', historiaVideosTerceiroAno),
    path('historia/videos/quartoAno/', historiaVideosQuartoAno),
    path('historia/videos/quintoAno/', historiaVideosQuintoAno),
    path('geografia/', geografia),
    path('geografia/jogos', geografiaJogos),
    path('geografia/jogos/primeiroAno/', geografiaJogosPrimeiroAno),
    path('geografia/jogos/segundoAno/', geografiaJogosSegundoAno),
    path('geografia/jogos/terceiroAno/', geografiaJogosTerceiroAno),
    path('geografia/jogos/quartoAno/', geografiaJogosQuartoAno),
    path('geografia/jogos/quintoAno/', geografiaJogosQuintoAno),
    path('geografia/atividades', geografiaAtividades),
    path('geografia/atividades/primeiroAno/', geografiaAtividadesPrimeiroAno),
    path('geografia/atividades/segundoAno/', geografiaAtividadesSegundoAno),
    path('geografia/atividades/terceiroAno/', geografiaAtividadesTerceiroAno),
    path('geografia/atividades/quartoAno/', geografiaAtividadesQuartoAno),
    path('geografia/atividades/quintoAno/', geografiaAtividadesQuintoAno),
    path('geografia/videos', geografiaVideos),
    path('geografia/videos/primeiroAno/', geografiaVideosPrimeiroAno),
    path('geografia/videos/segundoAno/', geografiaVideosSegundoAno),
    path('geografia/videos/terceiroAno/', geografiaVideosTerceiroAno),
    path('geografia/videos/quartoAno/', geografiaVideosQuartoAno),
    path('geografia/videos/quintoAno/', geografiaVideosQuintoAno),
    path('ciencias/', ciencias),
    path('ciencias/jogos', cienciasJogos),
    path('ciencias/jogos/primeiroAno/', cienciasJogosPrimeiroAno),
    path('ciencias/jogos/segundoAno/', cienciasJogosSegundoAno),
    path('ciencias/jogos/terceiroAno/', cienciasJogosTerceiroAno),
    path('ciencias/jogos/quartoAno/', cienciasJogosQuartoAno),
    path('ciencias/jogos/quintoAno/', cienciasJogosQuintoAno),
    path('ciencias/atividades', cienciasAtividades),
    path('ciencias/atividades/primeiroAno/', cienciasAtividadesPrimeiroAno),
    path('ciencias/atividades/segundoAno/', cienciasAtividadesSegundoAno),
    path('ciencias/atividades/terceiroAno/', cienciasAtividadesTerceiroAno),
    path('ciencias/atividades/quartoAno/', cienciasAtividadesQuartoAno),
    path('ciencias/atividades/quintoAno/', cienciasAtividadesQuintoAno),
    path('ciencias/videos', cienciasVideos),
    path('ciencias/videos/primeiroAno/', cienciasVideosPrimeiroAno),
    path('ciencias/videos/segundoAno/', cienciasVideosSegundoAno),
    path('ciencias/videos/terceiroAno/', cienciasVideosTerceiroAno),
    path('ciencias/videos/quartoAno/', cienciasVideosQuartoAno),
    path('ciencias/videos/quintoAno/', cienciasVideosQuintoAno),
    path('ingles/', ingles),
    path('ingles/jogos', inglesJogos),
    path('ingles/jogos/primeiroAno/', inglesJogosPrimeiroAno),
    path('ingles/jogos/segundoAno/', inglesJogosSegundoAno),
    path('ingles/jogos/terceiroAno/', inglesJogosTerceiroAno),
    path('ingles/jogos/quartoAno/', inglesJogosQuartoAno),
    path('ingles/jogos/quintoAno/', inglesJogosQuintoAno),
    path('ingles/atividades', inglesAtividades),
    path('ingles/atividades/primeiroAno/', inglesAtividadesPrimeiroAno),
    path('ingles/atividades/segundoAno/', inglesAtividadesSegundoAno),
    path('ingles/atividades/terceiroAno/', inglesAtividadesTerceiroAno),
    path('ingles/atividades/quartoAno/', inglesAtividadesQuartoAno),
    path('ingles/atividades/quintoAno/', inglesAtividadesQuintoAno),
    path('ingles/videos', inglesVideos),
    path('ingles/videos/primeiroAno/', inglesVideosPrimeiroAno),
    path('ingles/videos/segundoAno/', inglesVideosSegundoAno),
    path('ingles/videos/terceiroAno/', inglesVideosTerceiroAno),
    path('ingles/videos/quartoAno/', inglesVideosQuartoAno),
    path('ingles/videos/quintoAno/', inglesVideosQuintoAno),
]
